name: Build and Test

on:
  workflow_dispatch:
  pull_request:
  push:

env:
  BUILD_TYPE: Release

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build with CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} --config ${{ env.BUILD_TYPE }}
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: build