name: Build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build_and_test:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: (Ubuntu or MacOS) Build with CMake
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          cmake -S src -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: (Windows) Build with CMake
        if: matrix.os == 'windows-latest'
        run: |
          cmake -S src -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: build