name: Generate Documentation

on:
  workflow_dispatch:
  push:

jobs:
  generate_docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate documentation
        uses: mattnotmitt/doxygen-action@1.9.4

      - name: Upload the pages artifact
        uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: docs/
      
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: generate_docs
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the pages
        id: deployment
        uses: actions/deploy-pages@v1.0.10