name: Test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build_and_test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1

      - name: (Ubuntu or MacOS) Build with CMake
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          cmake -S src -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build build

      - name: (Windows) Build with CMake
        if: matrix.os == 'windows-latest'
        run: |
          cmake -S src -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build build --config Release

      - name: Run tests
        run: |
          cd build
          ctest